# Generated by Django 5.1 on 2024-08-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('leyenda', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
    ]
